# Databricks notebook source
from pyspark.sql.types import (
  StructType,
  StructField,
  StringType,
  DoubleType,
  TimestampType,
  LongType
)

struct_type_definition = {}

# COMMAND ----------

# MAGIC %md 
# MAGIC #Finance

# COMMAND ----------

# MAGIC %md
# MAGIC ##Accounting

# COMMAND ----------

# MAGIC %md
# MAGIC ###Copa

# COMMAND ----------

# MAGIC %md
# MAGIC ####1_co_pa100fe01_13_b

# COMMAND ----------

functional_domain, functional_subdomain, entity, sub_entity = 'finance', 'copa', 'copa', '1_co_pa100fe01_13_b'

struct_type_definition.setdefault(functional_domain, {}).setdefault(functional_subdomain, {}).setdefault(entity, {}).setdefault(sub_entity, {})

primary_keys = StructType([
  StructField("VRGAR", StringType(), False),
  StructField("VERSI", StringType(), False),
  StructField("PERIO", StringType(), False),
  StructField("PERIV", StringType(), False),
  StructField("BELNR", StringType(), False),
  StructField("POSNR", StringType(), False),
  StructField("CURTYPE", StringType(), False),
  StructField("VALUTYP", StringType(), False),
])

raw_schema = StructType([
  StructField('CURTYPE', StringType(), False),
  StructField('VALUTYP', StringType(), False),
  StructField('GJAHR', StringType(), True),
  StructField('PERIV', StringType(), False),
  StructField('PERIO', StringType(), False),
  StructField('WRTTP', StringType(), True),
  StructField('VRGAR', StringType(), False),
  StructField('VERSI', StringType(), False),
  StructField('CALWEEK', StringType(), True),
  StructField('BUKRS', StringType(), True),
  StructField('FKART', StringType(), True),
  StructField('PAPH3', StringType(), True),
  StructField('GSBER', StringType(), True),
  StructField('WWBSL', StringType(), True),
  StructField('KOKRS', StringType(), True),
  StructField('WWCAL', StringType(), True),
  StructField('WWCAT', StringType(), True),
  StructField('WWCFZ', StringType(), True),
  StructField('LAND1', StringType(), True),
  StructField('KNDNR', StringType(), True),
  StructField('KDGRP', StringType(), True),
  StructField('WWGC1', StringType(), True),
  StructField('WWGC2', StringType(), True),
  StructField('WWGC3', StringType(), True),
  StructField('WWGC4', StringType(), True),
  StructField('WWGC5', StringType(), True),
  StructField('KMHI01', StringType(), True),
  StructField('KMHI02', StringType(), True),
  StructField('KMHI03', StringType(), True),
  StructField('HIE04', StringType(), True),
  StructField('HIE05', StringType(), True),
  StructField('WWCBP', StringType(), True),
  StructField('VTWEG', StringType(), True),
  StructField('SPART', StringType(), True),
  StructField('WWIMP', StringType(), True),
  StructField('WWGEN', StringType(), True),
  StructField('WWINN', StringType(), True),
  StructField('WWPIN', StringType(), True),
  StructField('WWNAZ', StringType(), True),
  StructField('MATKL', StringType(), True),
  StructField('MTART', StringType(), True),
  StructField('WWMIS', StringType(), True),
  StructField('WWOPR', StringType(), True),
  StructField('RKAUFNR', StringType(), True),
  StructField('WWTPO', StringType(), True),
  StructField('WWTPC', StringType(), True),
  StructField('WWORI', StringType(), True),
  StructField('WERKS', StringType(), True),
  StructField('PRODH', StringType(), True),
  StructField('ARTNR', StringType(), True),
  StructField('WWTPP', StringType(), True),
  StructField('PRCTR', StringType(), True),
  StructField('WWRES', StringType(), True),
  StructField('WWDIV', StringType(), True),
  StructField('VKGRP', StringType(), True),
  StructField('VKBUR', StringType(), True),
  StructField('VKORG', StringType(), True),
  StructField('WWSLV', StringType(), True),
  StructField('BZIRK', StringType(), True),
  StructField('WWLDV', StringType(), True),
  StructField('WWKUN', StringType(), True),
  StructField('WWFAS', StringType(), True),
  StructField('WWZON', StringType(), True),
  StructField('WWGUS', StringType(), True),
  StructField('WWIDC', StringType(), True),
  StructField('WWCND', StringType(), True),
  StructField('WWTPV', StringType(), True),
  StructField('WWDTV', StringType(), True),
  StructField('WWTVA', StringType(), True),
  StructField('WWVAR', StringType(), True),
  StructField('VVQ40_ME', StringType(), True),
  StructField('REC_WAERS', StringType(), True),
  StructField('FADAT', StringType(), True),
  StructField('STO_BELNR', StringType(), True),
  StructField('STO_POSNR', StringType(), True),
  StructField('KSTAR', StringType(), True),
  StructField('KTOPL', StringType(), True),
  StructField('KSTRG', StringType(), True),
  StructField('BELNR', StringType(), False),
  StructField('WADAT', StringType(), True),
  StructField('POSNR', StringType(), False),
  StructField('PPRCTR', StringType(), True),
  StructField('BUDAT', StringType(), True),
  StructField('RBELN', StringType(), True),
  StructField('RPOSN', StringType(), True),
  StructField('KDPOS', StringType(), True),
  StructField('KAUFN', StringType(), True),
  StructField('PRZNR', StringType(), True),
  StructField('SKOST', StringType(), True),
  StructField('PSPNR', StringType(), True),
  StructField('VVS49', DoubleType(), True),
  StructField('VV063', DoubleType(), True),
  StructField('VV316', DoubleType(), True),
  StructField('VVE16', DoubleType(), True),
  StructField('VVE15', DoubleType(), True),
  StructField('VVG50', DoubleType(), True),
  StructField('VVG39', DoubleType(), True),
  StructField('VVG31', DoubleType(), True),
  StructField('VVG40', DoubleType(), True),
  StructField('VVG30', DoubleType(), True),
  StructField('VVG34', DoubleType(), True),
  StructField('VVG43', DoubleType(), True),
  StructField('VVG33', DoubleType(), True),
  StructField('VVG32', DoubleType(), True),
  StructField('VVG51', DoubleType(), True),
  StructField('VVG37', DoubleType(), True),
  StructField('VVG52', DoubleType(), True),
  StructField('VVG36', DoubleType(), True),
  StructField('VVG35', DoubleType(), True),
  StructField('VVG42', DoubleType(), True),
  StructField('VVG55', DoubleType(), True),
  StructField('VVG49', DoubleType(), True),
  StructField('VVG54', DoubleType(), True),
  StructField('VVG53', DoubleType(), True),
  StructField('VVG41', DoubleType(), True),
  StructField('VVG48', DoubleType(), True),
  StructField('VVG45', DoubleType(), True),
  StructField('VVG47', DoubleType(), True),
  StructField('VVG46', DoubleType(), True),
  StructField('VVG38', DoubleType(), True),
  StructField('VVG56', DoubleType(), True),
  StructField('VVG44', DoubleType(), True),
  StructField('VV362', DoubleType(), True),
  StructField('VV361', DoubleType(), True),
  StructField('VVF19', DoubleType(), True),
  StructField('VVF10', DoubleType(), True),
  StructField('VVF02', DoubleType(), True),
  StructField('VVF01', DoubleType(), True),
  StructField('VVF05', DoubleType(), True),
  StructField('VVF12', DoubleType(), True),
  StructField('VVF04', DoubleType(), True),
  StructField('VVF03', DoubleType(), True),
  StructField('VVF20', DoubleType(), True),
  StructField('VVF08', DoubleType(), True),
  StructField('VVF21', DoubleType(), True),
  StructField('VVF07', DoubleType(), True),
  StructField('VVF06', DoubleType(), True),
  StructField('VVF11', DoubleType(), True),
  StructField('VVF24', DoubleType(), True),
  StructField('VVF18', DoubleType(), True),
  StructField('VVF22', DoubleType(), True),
  StructField('VVF23', DoubleType(), True),
  StructField('VVF17', DoubleType(), True),
  StructField('VVF14', DoubleType(), True),
  StructField('VVF16', DoubleType(), True),
  StructField('VVF15', DoubleType(), True),
  StructField('VVF09', DoubleType(), True),
  StructField('VVF25', DoubleType(), True),
  StructField('VVF13', DoubleType(), True),
  StructField('VVF35', DoubleType(), True),
  StructField('VVF31', DoubleType(), True),
  StructField('VVF30', DoubleType(), True),
  StructField('VVF33', DoubleType(), True),
  StructField('VVF32', DoubleType(), True),
  StructField('VVF34', DoubleType(), True),
  StructField('VV873', DoubleType(), True),
  StructField('VVD10', DoubleType(), True),
  StructField('VV851', DoubleType(), True),
  StructField('VVD02', DoubleType(), True),
  StructField('VVD11', DoubleType(), True),
  StructField('VVD01', DoubleType(), True),
  StructField('VVE10', DoubleType(), True),
  StructField('VVD05', DoubleType(), True),
  StructField('VVE01', DoubleType(), True),
  StructField('VV312', DoubleType(), True),
  StructField('VVD04', DoubleType(), True),
  StructField('VVD03', DoubleType(), True),
  StructField('VV874', DoubleType(), True),
  StructField('VV382', DoubleType(), True),
  StructField('VVD08', DoubleType(), True),
  StructField('VV875', DoubleType(), True),
  StructField('VVD07', DoubleType(), True),
  StructField('VVD06', DoubleType(), True),
  StructField('VVD13', DoubleType(), True),
  StructField('VV878', DoubleType(), True),
  StructField('VVE03', DoubleType(), True),
  StructField('VVE04', DoubleType(), True),
  StructField('VV872', DoubleType(), True),
  StructField('VV876', DoubleType(), True),
  StructField('VV877', DoubleType(), True),
  StructField('VVD12', DoubleType(), True),
  StructField('VV786', DoubleType(), True),
  StructField('VV785', DoubleType(), True),
  StructField('VV782', DoubleType(), True),
  StructField('VV784', DoubleType(), True),
  StructField('VV783', DoubleType(), True),
  StructField('VV381', DoubleType(), True),
  StructField('VVD09', DoubleType(), True),
  StructField('VV313', DoubleType(), True),
  StructField('VV315', DoubleType(), True),
  StructField('VV317', DoubleType(), True),
  StructField('VVE02', DoubleType(), True),
  StructField('VVS51', DoubleType(), True),
  StructField('VVE14', DoubleType(), True),
  StructField('VVE17', DoubleType(), True),
  StructField('VVE12', DoubleType(), True),
  StructField('VVE13', DoubleType(), True),
  StructField('VVG21', DoubleType(), True),
  StructField('VVG10', DoubleType(), True),
  StructField('VVG02', DoubleType(), True),
  StructField('VVG11', DoubleType(), True),
  StructField('VVG01', DoubleType(), True),
  StructField('VVG05', DoubleType(), True),
  StructField('VVG14', DoubleType(), True),
  StructField('VVG04', DoubleType(), True),
  StructField('VVG03', DoubleType(), True),
  StructField('VVG22', DoubleType(), True),
  StructField('VVG08', DoubleType(), True),
  StructField('VVG23', DoubleType(), True),
  StructField('VVG07', DoubleType(), True),
  StructField('VVG06', DoubleType(), True),
  StructField('VVG13', DoubleType(), True),
  StructField('VVG26', DoubleType(), True),
  StructField('VVG20', DoubleType(), True),
  StructField('VVG25', DoubleType(), True),
  StructField('VVG24', DoubleType(), True),
  StructField('VVG12', DoubleType(), True),
  StructField('VVG19', DoubleType(), True),
  StructField('VVG16', DoubleType(), True),
  StructField('VVG18', DoubleType(), True),
  StructField('VVG17', DoubleType(), True),
  StructField('VVG09', DoubleType(), True),
  StructField('VVG27', DoubleType(), True),
  StructField('VVG15', DoubleType(), True),
  StructField('VVS29', DoubleType(), True),
  StructField('VVS28', DoubleType(), True),
  StructField('VV314', DoubleType(), True),
  StructField('VVG80', DoubleType(), True),
  StructField('VVG69', DoubleType(), True),
  StructField('VVG61', DoubleType(), True),
  StructField('VVG70', DoubleType(), True),
  StructField('VVG60', DoubleType(), True),
  StructField('VVG64', DoubleType(), True),
  StructField('VVG73', DoubleType(), True),
  StructField('VVG63', DoubleType(), True),
  StructField('VVG62', DoubleType(), True),
  StructField('VVG81', DoubleType(), True),
  StructField('VVG67', DoubleType(), True),
  StructField('VVG82', DoubleType(), True),
  StructField('VVG66', DoubleType(), True),
  StructField('VVG65', DoubleType(), True),
  StructField('VVG72', DoubleType(), True),
  StructField('VVG85', DoubleType(), True),
  StructField('VVG79', DoubleType(), True),
  StructField('VVG84', DoubleType(), True),
  StructField('VVG83', DoubleType(), True),
  StructField('VVG71', DoubleType(), True),
  StructField('VVG78', DoubleType(), True),
  StructField('VVG75', DoubleType(), True),
  StructField('VVG77', DoubleType(), True),
  StructField('VVG76', DoubleType(), True),
  StructField('VVG68', DoubleType(), True),
  StructField('VVG86', DoubleType(), True),
  StructField('VVG74', DoubleType(), True),
  StructField('VVQ40', DoubleType(), True),
  StructField('VV065', DoubleType(), True),
  StructField('VV064', DoubleType(), True),
  StructField('VV061', DoubleType(), True),
  StructField('VV062', DoubleType(), True),
  StructField('VV292', DoubleType(), True),
  StructField('VV290', DoubleType(), True),
  StructField('VV291', DoubleType(), True),
  StructField('VVE11', DoubleType(), True),
  StructField('DI_SEQUENCE_NUMBER', StringType(), False),
  StructField('DI_OPERATION_TYPE', StringType(), False)
 ])

bronze_schema = StructType(raw_schema.fields + [
  StructField('SOURCE', StringType(), False),
  StructField('BUSINESS_DATE', StringType(), False)
])

silver_schema = StructType(raw_schema.fields + [
  StructField('UpdateTimestamp', TimestampType(), False)
])

struct_type_definition[functional_domain][functional_subdomain][entity][sub_entity]["primary_keys"] = primary_keys
struct_type_definition[functional_domain][functional_subdomain][entity][sub_entity]["raw_schema"] = raw_schema
struct_type_definition[functional_domain][functional_subdomain][entity][sub_entity]["bronze_schema"] = bronze_schema
struct_type_definition[functional_domain][functional_subdomain][entity][sub_entity]["silver_schema"] = silver_schema

# COMMAND ----------

# MAGIC %md 
# MAGIC ###General Ledger

# COMMAND ----------

# MAGIC %md 
# MAGIC ####0FI_GL_4

# COMMAND ----------

functional_domain, functional_subdomain, entity, sub_entity = 'finance', 'accounting', 'general_ledger', '0FI_GL_4'

struct_type_definition.setdefault(functional_domain, {}).setdefault(functional_subdomain, {}).setdefault(entity, {}).setdefault(sub_entity, {})

primary_keys = StructType( [
        StructField("BUKRS", StringType(), False),
        StructField("FISCPER", StringType(), False),
        StructField("BELNR", StringType(), False),
        StructField("BUZEI", StringType(), False)
] )

raw_schema = StructType([
      StructField("BUKRS", StringType(), False),
      StructField("FISCPER", StringType(), False),
      StructField("BELNR", StringType(), False),
      StructField("BUZEI", StringType(), False),
      StructField("STATUSPS", StringType(), True),
      StructField("KTOPL", StringType(), True),
      StructField("HKONT", StringType(), True),
      StructField("KOART", StringType(), True),
      StructField("UMSKZ", StringType(), True),
      StructField("BLART", StringType(), True),
      StructField("BSCHL", StringType(), True),
      StructField("FISCVAR", StringType(), True),
      StructField("BLDAT", StringType(), True),
      StructField("BUDAT", StringType(), True),
      StructField("CPUDT", StringType(), True),
      StructField("VALUT", StringType(), True),
      StructField("AUGDT", StringType(), True),
      StructField("AUGBL", StringType(), True),
      StructField("KOKRS", StringType(), True),
      StructField("KOSTL", StringType(), True),
      StructField("PRCTR", StringType(), True),
      StructField("AUFNR", StringType(), True),
      StructField("PROJK", StringType(), True),
      StructField("WERKS", StringType(), True),
      StructField("GSBER", StringType(), True),
      StructField("FKBER", StringType(), True),
      StructField("PPRCT", StringType(), True),
      StructField("PARGB", StringType(), True),
      StructField("VBUND", StringType(), True),
      StructField("LCURR", StringType(), True),
      StructField("DMSOL", StringType(), True),
      StructField("DMHAB", StringType(), True),
      StructField("DMSHB", StringType(), True),
      StructField("WAERS", StringType(), True),
      StructField("WRSOL", StringType(), True),
      StructField("WRHAB", StringType(), True),
      StructField("WRSHB", StringType(), True),
      StructField("CURT2", StringType(), True),
      StructField("HWAE2", StringType(), True),
      StructField("DMSO2", StringType(), True),
      StructField("DMHA2", StringType(), True),
      StructField("DMSH2", StringType(), True),
      StructField("CURT3", StringType(), True),
      StructField("HWAE3", StringType(), True),
      StructField("DMSO3", StringType(), True),
      StructField("DMHA3", StringType(), True),
      StructField("DMSH3", StringType(), True),
      StructField("XBLNR", StringType(), True),
      StructField("XREF3", StringType(), True),
      StructField("AWREF", StringType(), True),
      StructField("AWGJA", StringType(), True),
      StructField("AWBUK", StringType(), True),
      StructField("AWKOK", StringType(), True),
      StructField("SGTXT", StringType(), True),
      StructField("XNEGP", StringType(), True),
      StructField("UPDMOD", StringType(), True),
      StructField("PS_POSID", StringType(), True),
      StructField("ZUONR", StringType(), True),
      StructField("AWTYP", StringType(), True),
      StructField("AWKEY", StringType(), True),
      StructField("BSTAT", StringType(), True),
      StructField("DMBTR", StringType(), True),
      StructField("DMBE2", StringType(), True),
      StructField("DMBE3", StringType(), True),
      StructField("GJAHR", StringType(), True),
      StructField("MANDT", StringType(), True),
      StructField("MONAT", StringType(), True),
      StructField("SHKZG", StringType(), True),
      StructField("WRBTR", StringType(), True),
      StructField("KUNNR", StringType(), True),
      StructField("BUZID", StringType(), True),
      StructField("MWART", StringType(), True),
      StructField("TXGRP", StringType(), True),
      StructField("ANBWA", StringType(), True),
      StructField("LIFNR", StringType(), True),
      StructField("TCODE", StringType(), True),
      StructField("HWBAS", StringType(), True),
      StructField("ZZHWBAS", StringType(), True),
      StructField("ZZDEBI", StringType(), True),
      StructField("XREF2_HD", StringType(), True),
      StructField("BKTXT", StringType(), True),
      StructField("GLVOR", StringType(), True),
      StructField("PERNR", StringType(), True),
      StructField("FISTL", StringType(), True),
      StructField("GEBER", StringType(), True),
      StructField("KTOSL", StringType(), True),
      StructField("MWSKZ", StringType(), True),
      StructField("MATNR", StringType(), True),
      StructField("ZZ_USER", StringType(), True),
      StructField("ZZ_USRCLASS", StringType(), True),
      StructField("ANLN1", StringType(), True),
      StructField("CPUTM", StringType(), True),
      StructField("BWTAR", StringType(), True),
      StructField("BUSTW", StringType(), True),
      StructField("EBELN", StringType(), True),
      StructField("EBELP", StringType(), True),
      StructField("RSTGR", StringType(), True),
      StructField("DI_SEQUENCE_NUMBER", StringType(), False),
      StructField("DI_OPERATION_TYPE", StringType(), False),
      StructField("STJAH", StringType(), True),
      StructField("DABRZ", StringType(), True),
      StructField("AUGCP", StringType(), True),
      StructField("XREF1", StringType(), True),
      StructField("BVTYP", StringType(), True),
      StructField("DOCCAT", StringType(), True)
])

bronze_schema = StructType(raw_schema.fields)

silver_schema = StructType(bronze_schema.fields + [
  StructField('SOURCE', StringType(), False),
  StructField('DATE_INSERT', TimestampType(), False)
])

struct_type_definition[functional_domain][functional_subdomain][entity][sub_entity]["primary_keys"] = primary_keys
struct_type_definition[functional_domain][functional_subdomain][entity][sub_entity]["raw_schema"] = raw_schema
struct_type_definition[functional_domain][functional_subdomain][entity][sub_entity]["bronze_schema"] = bronze_schema
struct_type_definition[functional_domain][functional_subdomain][entity][sub_entity]["silver_schema"] = silver_schema